### PR TITLE
Feature/stores

### PR DESCRIPTION
**Pull request by YehielShamir**

### CODE REVIEW

**Comment by elchanan1357** [comment]
add stores to TechWorld

**Comment by YehielShamir** [comment]
Smuel, well done!!!

**Comment by elchanan1357** [comment]
add stores to the TechWorld

**Comment by elchanan1357** [comment]
.

**Comment by elchanan1357** [comment]
add stores to the TechWorld

**Comment by elchanan1357** [comment]
add stores to the TechWorld

**Pull request closed without merging**
